apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
  spec:
    containers:
    - name: mongodb
      image: mongo:3.4.1
      command:
      - mongod
      - --replSet
      - rs0
      ports:
      - containerPort: 27017
        name: web
    # Initialisation container for Mongo - sleeps forever
    - name: mongo-init
      image: mongo:3.4.1
      command:
      - bash
      - /config/init.sh
      volumeMounts:
      - name: config
        mountPath: /config
    volumes:
    - name: config
      configMap:
        name: "mongo-init"