apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    #!/bin/bash

    # Wait until names resolve
    until ping -c 1 ${HOSTNAME}.mongo; do
      echo "waiting for DNS (${HOSTNAME}.mongo)..."
      sleep 2
    done

    until /usr/bin/mongo --eval 'printjson(db.serverStatus())'; do
      echo "Connecting to Local Mongo..."
      sleep 2
    done

    echo "Connected to Local."

    HOST=mongo-0.mongo:27017

    until /usr/bin/mongo --host=${HOST} --eval 'printjson(db.serverStatus())'; do
       echo "Connecting to Remote Mongo..."
      sleep 2
    done

    echo "Connected to Remote."

    if [[ "${HOSTNAME}" != 'mongo-0' ]]; then
      until /usr/bin/mongo --host=${HOST} --eval 'printjson(rs.status())' \
          | grep -v "no replset config received yet by Mongo"; do
        echo "Connecting to Remote Mongo..."
        sleep 2
      done

      echo "adding self to mongo-0"
      /usr/bin/mongo --host=${HOST} --eval="printjson(rs.add ('${HOSTNAME}.mongo'))"
    fi

    if [[ "${HOSTNAME}" == 'mongo' ]]; then
      echo "initialising the replicaset..."
      /usr/bin/mongo --eval="printjson(rs.initiate({'_id': 'rs0', 'members': \ 
        [{'_id':0, 'host': 'mongo-0.mongo:27017'}]}))"
    fi

    echo "initialised..."

    while true; do
      sleep 3600
    done
